name: sq_hub_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/
# Articles/CoreFoundationKeys.html
version: 2.2.00+2029

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.0
  cached_network_image: ^3.3.1
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  pull_to_refresh: ^2.0.0
  package_info_plus: ^8.0.0
  platform: ^3.1.0
  card_swiper : ^3.0.1
  flutter_keyboard_visibility: ^6.0.0
  scan: ^1.6.0
  ai_barcode: ^3.2.7
  permission_handler: ^11.3.0
  badges: ^2.0.3
  flutter_cupertino_datetime_picker: ^3.0.0
  get: ^4.6.6
  flutter_smart_dialog: ^4.9.0+5
  image_picker: ^1.1.0
  extended_image: ^8.0.0
  flutter_image_compress: ^2.3.0
  image_editor: ^1.1.0
  path_provider: ^2.1.0
  date_format: ^2.0.7
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.0
  store_redirect: ^2.0.1
  flutter_stripe: ^10.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.10+1
  ff_stars: ^1.2.5
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.15.0
  flutter_widget_from_html: ^0.15.0
  pinput: ^4.0.0
  showcaseview: ^2.0.3
  sign_in_with_apple: ^6.0.0
  flutter_web_auth: ^0.5.0
  waterfall_flow: ^3.0.2
  decimal: ^2.3.3
  numberpicker: ^2.1.2
  flutter_slidable: ^3.1.0

  flutter_cache_manager: ^3.3.1
  local_notifications_for_us: 1.0.4
#  flutter_local_notifications_linux: ^0.5.0
  dotted_border: ^2.1.0
  geolocator: ^13.0.0
  flutter_ringtone_player: ^4.0.0
  flutter_screenutil: ^5.9.1
  google_sign_in: ^6.2.0
  lottie: ^3.1.0

  just_audio: ^0.9.40
  flutter_app_badger:
    path: plugins/flutter_app_badger
  flutter_rating_bar: ^4.0.1

  file_picker: ^8.0.0
  libphonenumber_plugin: 0.3.1
  equatable: ^2.0.5
  collection: ^1.18.0
  qr_flutter: ^4.1.0
  csslib: ^1.0.0
  onesignal_flutter: ^5.2.0
  in_app_purchase: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  in_app_purchase: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/city.json
    - assets/data/country.json
    - assets/flags/

  fonts:
    - family: Black-2
      fonts:
        - asset: assets/fonts/Montserrat-Black-2.ttf
    - family: Light-6
      fonts:
        - asset: assets/fonts/Montserrat-Light-6.ttf
    - family: Medium-7
      fonts:
        - asset: assets/fonts/Montserrat-Medium-7.ttf
    - family: DIN-Condensed-Bold
      fonts:
        - asset: assets/fonts/DIN-Condensed-Bold.ttf
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: wy
      fonts:
        - asset: assets/fonts/wy.ttf
    - family: Blak_W90_Ultra
      fonts:
        - asset: assets/fonts/Blak_W90_Ultra.ttf
    - family: zenDots
      fonts:
        - asset: assets/fonts/ZenDots-Regular.ttf