org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=--add-opens java.base/java.io=ALL-UNNAMED
#systemProp.http.proxyHost=127.0.0.1
#systemProp.http.proxyPort=1087
#systemProp.https.proxyHost=127.0.0.1
#systemProp.https.proxyPort=1087
#org.gradle.caching=true
#org.gradle.console=verbose
#org.gradle.debug=true
#org.gradle.logging.level=debug

