// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmYBoVJ0sieOiO0ElEB1D48hUAaqdibDM',
    appId: '1:760458602993:android:723c8e8653df547535bc50',
    messagingSenderId: '760458602993',
    projectId: 'sidequest-b26dd',
    storageBucket: 'sidequest-b26dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKsK0Qm3So2JCTTJcFMXs7Q4rp3M8uL08',
    appId: '1:760458602993:ios:8ecdad42dd09036635bc50',
    messagingSenderId: '760458602993',
    projectId: 'sidequest-b26dd',
    storageBucket: 'sidequest-b26dd.firebasestorage.app',
    // iosClientId: 'com.googleusercontent.apps.40635894328-lgg8oi13171vnaijmp0b35mp1cp3famc',
    iosBundleId: 'com.uk.co.sq.hub',
  );
}
